#ifndef APPLICATION_SETTINGS_H_
#define APPLICATION_SETTINGS_H_

#define WINDOW_POSX		300
#define WINDOW_POSY		300

#define WINDOW_WIDTH	960
#define WINDOW_HEIGHT	600

#define WINDOW_NAME		"TP2 - Courbes et trajectoires"

#define	FPS				60.0f
#define FRAME_DURATION	1000/FPS

#endif //APPLICATION_SETTINGS_H_